# Generated by Django 5.1.2 on 2024-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
