# Generated by Django 5.1.2 on 2024-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('2g', '2G Avadanlıqlar'), ('4g', '4G Avadanlıqlar'), ('sensor', 'Temperatur Sensoru')], max_length=20),
        ),
    ]
