# Generated by Django 5.1.2 on 2024-11-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_portfolioitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('2g', '2G Avadanlıqlar'), ('4g', '4G Avadanlıqlar'), ('sensor', 'Sensorlar')], max_length=20),
        ),
    ]
