# Generated by Django 5.1.2 on 2024-11-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
