# Generated by Django 5.1.2 on 2024-11-23 12:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
