# Generated by Django 5.1.2 on 2024-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_faq_answer_az_faq_answer_en_faq_answer_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('2g', '2G Avadanlıqlar'), ('4g', '4G Avadanlıqlar'), ('sensor', 'Sensorlar'), ('topography', 'Topoqrafiya Avadanlıqları')], max_length=20),
        ),
    ]
